name: Build and Deploy Portfolio

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set working directory to Portfolio
      - name: Set working directory to Portfolio
        working-directory: ./Portfolio
        run: echo "Entered Portfolio directory"

      # Step 3: Install dependencies
      - name: Install dependencies
        working-directory: ./Portfolio
        run: |
          npm install
          npm install sass typescript

      # Step 4: Compile SCSS to CSS
      - name: Compile SCSS
        working-directory: ./Portfolio
        run: |
          npx sass src/Styles/Main.scss src/Styles/Main.css

      # Step 5: Compile TypeScript
      - name: Compile TypeScript
        working-directory: ./Portfolio
        run: |
          npx tsc --outDir dist

      # Step 6: Upload compiled files as artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # Step 7: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
